config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'

  resources :rooms do
    get :post, on: :collection
    get :search, on: :collection
    get :reservations, on: :collection
  end

  resources :user_rooms

  devise_for :users, :controllers => {
    :confirmations => 'users/confirmations',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
  }

  resources :users do
    get :profile, on: :collection
    get :account, on: :collection
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user , optional: true#post index
  has_many :user_rooms
  has_many :users, through: :user_rooms

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :address, presence: true

  mount_uploader :image, ImageUploader

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all #allメソッドはusersテーブルのレコードを全て取得できるメソッド
  end

  def new
    if !user_signed_in?
      redirect_to "/users/sign_in"
    else
      @room = Room.new
    end
  end

  def create
    @room = Room.new(def_params)
    if @room.save
      flash[:notice] = "新規登録しました"
      redirect_to @room
    else
      render "new"
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def edit
    @room = Room.find(params[:id])
    @user = current_user
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(def_params)
      flash[:notice] = "ID「#{@room.id}」の情報を更新しました"
      redirect_to :rooms
    else
      render "edit"
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    flash[:notice] = "削除しました"
    redirect_to :rooms
  end

  # 部屋検索結果
  def search
    # エリアと部屋名から検索
    # @rooms = Room.where('address LIKE ?', "%#{params[:area]}%").where('name LIKE ?', "%#{params[:name]}%")

    # エリア、部屋名、説明文から検索
    @rooms = Room.where("address LIKE ?", "%#{params[:area]}%").where(["name LIKE (?) OR description LIKE(?)", "%#{params[:name]}%", "%#{params[:name]}%"])
  end

  # ログインが必要な物

  # 登録した部屋一覧
  def post
    if !user_signed_in?
      redirect_to "/users/sign_in" # isnot login
    else
      @rooms = Room.where(user_id: current_user.id)
      # @rooms = current_user.rooms #リレーション読み込みできない?
    end
  end

  # 予約一覧
  def reservations
    if !user_signed_in?
      redirect_to "/users/sign_in" # isnot login
    else
      @reservations = UserRoom.where(user_id: current_user.id).order(:date_start)
    end
  end

  private

  # create,updateの共通パラメータ（ストロング）
  def def_params
    params.require(:room).permit(:address, :name, :description, :image, :price, :user_id)
  end
end

app/views/rooms/edit.html.erb
<h2>新規作成</h2>

<%= form_with model: @room, local: true do |f| %>

  <table>
    <tr>
      <th><%= f.label :address ,"住所" %></th>
      <td><%= f.text_field :address %></td>
    </tr>

    <tr>
      <th><%= f.label :name ,"名前" %></th>
      <td><%= f.text_field :name %></td>
    </tr>

    <tr>
      <th><%= f.label :description ,"説明文" %></th>
      <td><%= f.text_field :description %></td>
    </tr>

    <tr>
      <th><%= f.label :price ,"1人あたりの価格" %></th>
      <td><%= f.text_field :price %></td>
    </tr>
  </table>

  <%= f.hidden_field :user_id, value:@user.id %>

  <div>
    <ul>
      <li><%= f.submit "登録する"%></li>
      <li><%= link_to "一覧に戻る", :rooms %></li>
    </ul>
  </div>
<% end %>

app/views/rooms/index.html.erb
<div id="slideshow" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-touch="false">
  <% if  flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>

  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="5000">
	  <img src="/assets/slideshow_01.jpg" alt="スライド画像" class="d-block w-100">
	</div>
	<div class="carousel-item" data-bs-interval="5000">
	  <img src="/assets/slideshow_02.jpg" alt="スライド画像" class="d-block w-100">
	</div>
	<div class="carousel-item" data-bs-interval="5000">
	  <img src="/assets/slideshow_03.jpg" alt="スライド画像" class="d-block w-100">
	</div>
  </div>
  <div id="slideshow_logo">
    <div class="slideshow_logo_title">KASHI × KARI</div>
	    <p class="slideshow_logo_desc">部屋と人をつなぐプラットフォーム</p>
      <%= form_with url: search_rooms_path, method: :get, local: true do |f| %>
        <div class="row  align-items-center pb-4">
          <div class="col-auto p-1">
            <%= f.text_field :area, placeholder: "エリア", class: "form-control" %>
          </div>
          <div class="col-auto p-1">
            <%= f.text_field :name, placeholder: "キーワード", class: "form-control"%>
          </div>
          <div class="col-auto p-1">
            <%= f.submit "検索", class: "btn btn-primary"%>
          </div>
        </div>  
      <% end %>
  </div>
</div>


<div id="main">
  <div>
    <h3>おすすめエリア</h3>
	  <div class="row row-cols-3 pb-5">
	    <div class="col">
	      <a class="card" href="/rooms/search?area=東京&name=">
		    <img src="/assets/slideshow_01_s.jpg" alt="" class="card-img-top">
		    <div class="card-body">
		      <h5>東京</h5>
		    </div>
		  </a>
		</div>
		
		<div class="col">
		  <a class="card" href="/rooms/search?area=沖縄&name=">
  		    <img src="/assets/slideshow_03_s.jpg" alt="" class="card-img-top">
		    <div class="card-body">
  		      <h5>沖縄</h5>
		    </div>
		  </a>
		</div>
		
		<div class="col">
		  <a class="card" href="/rooms/search?area=北海道&name=">
		    <img src="/assets/slideshow_02_s.jpg" alt="" class="card-img-top">
		    <div class="card-body">
		      <h5>北海道</h5>
		    </div>
		  </a>
		</div>

	  </div>
  </div>
  
  <div>
    <h3>人気のキーワード</h3>
    <div class="row row-cols-3 pb-5">
	    <div class="col">
	      <a class="card" href="/rooms/search?area=&name=海が見える">
		      <img src="/assets/slideshow_03_s.jpg" alt="" class="card-img-top">
		      <div class="card-body">
  		      <h5>海が見える</h5>
	  	    </div>
		    </a>
		  </div>
		
      <div class="col">
        <a class="card" href="/rooms/search?area=&name=山の中">
          <img src="/assets/slideshow_02_s.jpg" alt="" class="card-img-top">
          <div class="card-body">
            <h5>山の中</h5>
          </div>
        </a>
      </div>
      
      <div class="col">
        <a class="card" href="/rooms/search?area=&name=夜景が綺麗">
          <img src="/assets/slideshow_01_s.jpg" alt="" class="card-img-top">
          <div class="card-body">
            <h5>夜景が綺麗</h5>
            </div>
        </a>
      </div>
	  </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div id="main">
  <div id="pannel_center" class="pannel_e">
    <h4 class="pb-4">部屋を登録する</h4>

    <%= form_with model: @room, local: true do |f| %>
      <%#=render "shared/error", obj: @room %>
      <div class="w-75 m-auto text-start">

        <div class="row pb-4">
          <div class="ps-0 pb-1">
            <%= f.label :image,"部屋の写真", class:"pe-2" %>
            <span class="badge bg-secondary">任意</span>
          </div>
          <%= f.file_field :image, id:"user_img", class: "form-control" %>
        </div>
        <div class="row pb-4">
          <% if @room.image.present? %>
            <%= image_tag @room.image, id: :img_prev %>
          <% else %>
            <img id="img_prev" src="/assets/default_room.jpg">
          <% end %>
          <%= f.hidden_field :image_cache %>
        </div>

        <div class="row pb-4">
          <div class="ps-0">
            <%= f.label :address ,"住所", class: "pe-2" %>
            <span class="badge bg-danger">必須</span>
          </div>
          <%= f.text_field :address, class: "form-control" %>
        </div>

        <div class="row pb-4">
          <div class="ps-0">
            <%= f.label :name ,"部屋名", class: "pe-2" %>
            <span class="badge bg-danger">必須</span>
          </div>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="row pb-4">
          <div class="ps-0">
            <%= f.label :description ,"紹介文", class: "pe-2" %>
            <span class="badge bg-danger">必須</span>
          </div>
          <%= f.text_area :description, class: "form-control" %>
        </div>
        
        <div class="row pb-4">
          <div class="ps-0">
            <%= f.label :price ,"1人あたりの価格", class: "pe-2" %>
            <span class="badge bg-danger">必須</span>
          </div>
          <%= f.number_field :price, class: "form-control" %>
        </div>
        
        <%= f.hidden_field :user_id, value: current_user.id %>

        <div class="row pb-5">
          <%= f.submit "新規登録する",  class: "btn btn-primary" %>
        </div>

     </div>
    <% end %>
  </div>
</div>

<%= javascript_pack_tag 'imagepreview' %>

app/views/rooms/post.html.erb
<div id="main">
  <h2>登録した部屋一覧</h2>

  <div class="row row-cols-4 roomlist">

    <% if @rooms.size == 0 %>
      <p>現在登録はありません</p>
    <% end %>

    <% @rooms.each do |room| %>
      <div class="col">
        <div class="card h-100">
          <% if room.image? %>
            <% imgsrc = room.image.url %>
          <% else %>
            <% imgsrc = "/assets/slideshow_01_s.jpg" %>
          <% end %>
          <img src="<%= imgsrc %>" alt="roomthum" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title"><%= room.name %></h5>
            <p class="card-text room-address"><%= room.address %></p>
            <p class="card-text"><%= room.description %></p>
            <p class="card-text">1泊1人あたり:<%= room.price.to_s(:delimited) %>円</p>
          </div>
          <div class="card-body">
            <%= link_to "確認", room, class: "card-link" %>
            <%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか？" } , class: "card-link"%>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/rooms/reservations.html.erb
<div id="main">
  <% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% elsif flash[:alert]%>
    <div class="alert alert-denger"><%= flash[:alert] %></div>
  <% end %>

  <h2>予約一覧</h2>
  <% if @reservations.size == 0 %>
    <p>現在登録はありません</p>
  <% end %>

  <div class="row row-cols-3 roomlist">
    <% @reservations.each do |reservation| %>
      <% room = reservation.room %>
      <%
        if room != nil
          room_name = room.name
          room_address = room.address
        else
          room_name = "削除されたホテル"
          room_address = "-"
        end
        %>
      <div class="col">
        <div class="card h-100">
          <% if room.image? %>
            <% imgsrc = room.image.url %>
          <% else %>
            <% imgsrc = "/assets/slideshow_01_s.jpg" %>
          <% end %>
          <img src="<%= imgsrc %>" alt="roomthum" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title"><%= room_name %></h5>
            <p class="card-text room-address"><%= room_address %></p>
            <p class="card-text">宿泊人数：<%= reservation.member %>人</p>
            <p class="card-text">
              <%= (reservation.date_end.to_date - reservation.date_start.to_date).to_i %>泊：
              <%= reservation.price.to_s(:delimited) %>円
            </p>
            <p class="card-text">
              チェックイン：<%= reservation.date_start.strftime("%Y年%m月%d日") %><br>
              チェックアウト：<%= reservation.date_end.strftime("%Y年%m月%d日") %>
            </p>
          </div>
          <div class="card-body">
            <%= link_to "部屋詳細", room, class: "card-link" %>
            <%= link_to "キャンセル", user_room_path(id:reservation.id), method: :delete, data: { confirm: "本当にキャンセルしますか？" },  class: "card-link" %>
          </div>
        </div>
      </div>
    <% end #each end %>
  </div>
  <!--roomlist end-->
</div>
<!--main end-->

app/views/rooms/search.html.erb
<div id="main">
  <%
  if params[:area]!=""
    area = "『#{params[:area]}』"
  end
  if params[:name]!=""
    name = "『#{params[:name]}』"
  end
  %>
  <% if params[:area]!="" || params[:name]!="" %>
    <h2><%= area %><%= name %>の検索結果</h2>
  <% else %>
    <h2>部屋一覧</h2>
  <% end %>
  
  <div class="row row-cols-4 roomlist">
  
    <% if @rooms.size == 0 %>
      <p>現在登録はありません</p>
    <% end %>

    <% @rooms.each do |room| %>
      <div class="col">
	      <a href="/rooms/<%= room.id %>" class="card h-100">
          <% if room.image? %>
            <% imgsrc = room.image.url %>
          <% else %>
            <% imgsrc = "/assets/slideshow_01_s.jpg" %>
          <% end %>
          <img src="<%= imgsrc %>" alt="roomthum" class="card-img-top">
	        <div class="card-body">
  	        <h5 class="card-title"><%= room.name %></h5>
		        <p class="card-text room-address"><%= room.address %></p>
		        <p class="card-text"><%= room.description %></p>
            <p class="card-text">1泊1人あたり:<%= room.price.to_s(:delimited) %>円</p>
            <p class="card-text room-address">登録者：
              <% user = User.find(room.user_id) %>
              <% if user.image? %>
                <% iconsrc = user.image.thumb.url %>
              <% else %>
                <% iconsrc = "/assets/default_icon.jpg" %>
              <% end %>
              <img src="<%= iconsrc %>" alt="ユーザーアイコン" width="20px">
              <%= user.name %>
            </p>
	        </div>
	      </a>
	    </div>
    <% end %>

  </div>
</div>

app/views/rooms/show.html.erb
<div id="main">
  <% if  flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
    <ul class="alert alert-danger">
      <% flash[:alert].each do |alert| %>
        <li><%= alert %></li>
      <% end %>
    </ul>
  <% end %>

  <h2><%= @room.name %></h2>
  <p><%= @room.address %></p>

  <div class="row">
    <div class="col">

      <% if @room.image? %>
            <% imgsrc = @room.image.url %>
          <% else %>
            <% imgsrc = "/assets/slideshow_01_s.jpg" %>
          <% end %>
      <img src="<%= imgsrc %>" alt="roomimage" class="img-fluid pb-3">

	    <p>1泊1人あたり:<%= @room.price.to_s(:delimited) %>円</p>
      <p><%= @room.description %></p>
	  </div>
	
	  <div class="col-3 pannel_e">
      <h4 class="pt-3 pb-3">予約する</h4>
    
      <% if user_signed_in? %>
        <%= form_with model: @user_room, :url=>{ :controller=>"user_rooms", :action=>"new"} , method: :get do |f| %>
        <%#= render "shared/error", obj: @room %>
          <div class="pb-3">
            <%= f.label :date_start ,"チェックイン" %>
            <%= f.date_field :date_start, class:"form-control" %>
          </div>
          <div class="pb-3">
            <%= f.label :date_end ,"チェックアウト" %>
            <%= f.date_field :date_end, class:"form-control" %>
          </div>
          <div class="pb-4">
            <%= f.label :member ,"利用人数" %>
            <%= f.number_field :member, class:"form-control" %>
          </div>
          
          <%= f.hidden_field :price, value:@room.price %>
          <%= f.hidden_field :user_id, value:current_user.id %>
          <%= f.hidden_field :room_id, value:@room.id %>

          <div>
            <%= f.submit "確認画面へ", id:"submitbtn" , class: "btn btn-primary form-control"%>
          </div>

          <!--入力補助-->
            <script>
              if (sessionStorage.getItem("reservations_inputs")!=null){
                var inputs = JSON.parse(sessionStorage.getItem("reservations_inputs"));
                document.getElementById("date_start").value = inputs['date_start'];
                document.getElementById("date_end").value = inputs['date_end'];
                document.getElementById("member").value = inputs['member'];
              }

              document.getElementById('submitbtn').addEventListener('click',function(){
                var inputs = {
                  'date_start' : document.getElementById("date_start").value,
                  'date_end' : document.getElementById("date_end").value,
                  'member' : document.getElementById("member").value
                }
                sessionStorage.setItem('reservations_inputs', JSON.stringify(inputs));
              });
            </script>
          <!--入力補助end-->
        <% end #form end %>
      <% else %>
        <%# if not login %>
        <p>予約にはログインが必要です。</p>
        <%= link_to "ログイン", new_user_session_path, class: 'btn btn-primary' %>
      <% end #if login end %>
      
    </div><!--pannel_e end-->

  </div>
</div>